/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package finalproject;

/**
 *
 * @author Anjelin Ligiana Nainggolan
 */

import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Connection conn = null;  // koneksi database

    public Dashboard() {
        initComponents();
        connect();             // koneksi ke database MySQL
        
        ManageRoom.addActionListener(evt -> ManageRoomActionPerformed(evt));
        CheckIn.addActionListener(evt -> CheckInActionPerformed(evt));
        close.addActionListener(evt -> closeActionPerformed(evt));
    }

    private void connect() {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/p2h_oovp", "root", "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection Failed: " + e.getMessage());
            System.exit(0);
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        ManageRoom = new javax.swing.JButton();
        CheckIn = new javax.swing.JButton();
        CheckOut = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/p2h_attribute/close.png"))); // NOI18N
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 60, -1));

        ManageRoom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManageRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/p2h_attribute/ManageRoom.png"))); // NOI18N
        ManageRoom.setText("Manage Room");
        getContentPane().add(ManageRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, -1, 59));

        CheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/p2h_attribute/CheckIn.png"))); // NOI18N
        CheckIn.setText("Check In");
        getContentPane().add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, 195, 59));

        CheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/p2h_attribute/CheckOut.png"))); // NOI18N
        CheckOut.setText("Check Out");
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 195, 59));

        LogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/p2h_attribute/LogOut.png"))); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setMaximumSize(new java.awt.Dimension(800, 600));
        LogOut.setMinimumSize(new java.awt.Dimension(800, 600));
        LogOut.setPreferredSize(new java.awt.Dimension(1366, 768));
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 195, 59));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 102));
        jButton1.setText("@anjelin.ln");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/p2h_attribute/Homepage.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1370, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        new Checkout().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_CheckOutActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        int yes=JOptionPane.showConfirmDialog(this,"are you Logout this page?","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (yes==JOptionPane.YES_OPTION)
            new Login().setVisible (true);

// TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HelpPage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void ManageRoomActionPerformed(java.awt.event.ActionEvent evt) {
        new ManageRoom().setVisible(true);
    // TODO: buka form baru atau tampilkan panel
    }

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {
        new BookingRoom().setVisible(true);
    // TODO: buka form CheckIn
    }

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {
        int yes=JOptionPane.showConfirmDialog(this,"are you sure close this Application?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (yes==JOptionPane.YES_OPTION)
            System.exit(0); // keluar aplikasi
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }
    // End of variables declaration                   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckIn;
    private javax.swing.JButton CheckOut;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ManageRoom;
    private javax.swing.JButton close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}